const types = Object.freeze({
    // Actions for Todo
    CHANGE_LOADING: "CHANGE_LOADING",
    SET_TASKS: "SET_TASKS",
    ADD_TASK: "ADD_TASK",
    EDIT_TASK: "EDIT_TASK",
    DEL_ONE_TASK: "DEL_ONE_TASK",
    CHECK_TASK: "CHECK_TASK",
    CHECK_ALL_TASKS: "CHECK_ALL_TASKS",
    DEL_SEL_TASKS: "DEL_SEL_TASKS",
    OPEN_ADD_OR_EDIT_TASK_MODAL: "OPEN_ADD_OR_EDIT_TASK_MODAL",
    SHOW_HIDE_DELETE_MODAL: "SHOW_HIDE_DELETE_MODAL",
    SET_CHANGABLE_TASK: "SET_CHANGABLE_TASK",
    SET_ERROR: "SET_ERROR",
    CHANGE_STATUS: "CHANGE_STATUS",

    // Actions for Contact
    CHANGE_VALUES: "CHANGE_VALUES",
    SUBMIT_FORM: "SUBMIT_FORM",
    RESET_FORM: "RESET_FORM",

    //Actions for OneTask
    SET_ONE_TASK: "SET_ONE_TASK",
    OPEN_EDIT_TASK_MODAL: "OPEN_EDIT_TASK_MODAL",

    //Actions for Search
    SET_DROPDOWN_VALUE: "SET_DROPDOWN_VALUE",
    CHANGE_SEARCH: "CHANGE_SEARCH",
    SET_DATE: "SET_DATE",
    RESET_SEARCH: "RESET_SEARCH",
    SHOW_FILTER: "SHOW_FILTER"
})


export default types;