const types = Object.freeze({
    // Actions for Todo
    CHANGE_LOADING: "CHANGE_LOADING",
    SET_TASKS: "SET_TASKS",
    ADD_TASK: "ADD_TASK",
    EDIT_TASK: "EDIT_TASK",
    DEL_ONE_TASK: "DEL_ONE_TASK",
    CHECK_TASK: "CHECK_TASK",
    CHECK_ALL_TASKS: "CHECK_ALL_TASKS",
    DEL_SEL_TASKS: "DEL_SEL_TASKS",
    OPEN_ADD_OR_EDIT_TASK_MODAL: "OPEN_ADD_OR_EDIT_TASK_MODAL",
    SHOW_HIDE_DELETE_MODAL: "SHOW_HIDE_DELETE_MODAL",
    SET_CHANGABLE_TASK: "SET_CHANGABLE_TASK",

    // Actions for Contact
    CHANGE_VALUES: "CHANGE_VALUES",
    SUBMIT_FORM: "SUBMIT_FORM"
})


export default types;